//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weeklyrecords
    {
        public int Record_id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<double> Vaha { get; set; }
        public Nullable<double> Prsa { get; set; }
        public Nullable<double> Bricho { get; set; }
        public Nullable<double> Pas { get; set; }
        public Nullable<double> Zadek { get; set; }
        public Nullable<double> Ruka_prava { get; set; }
        public Nullable<double> Ruka_leva { get; set; }
        public Nullable<double> Stehno_leve { get; set; }
        public Nullable<double> Stehno_prave { get; set; }
        public Nullable<double> Lytko_prave { get; set; }
        public Nullable<double> Lytko_leve { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> Comment_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
